# Generated by Django 5.2 on 2025-04-22 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LunchConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.IntegerField(default=650, help_text="お弁当価格")),
                ("subsidy", models.IntegerField(default=230, help_text="会社補助額")),
                (
                    "monthly_limit",
                    models.IntegerField(default=3780, help_text="会社負担上限額"),
                ),
            ],
            options={
                "verbose_name": "ランチ設定",
                "verbose_name_plural": "ランチ設定",
            },
        ),
    ]
