# Generated by Django 5.2 on 2025-04-30 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lunch", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_date", models.DateField()),
                (
                    "vendor",
                    models.CharField(
                        choices=[
                            ("veg17", "ベジタブルディッシュ17"),
                            ("yamajin", "やまじん"),
                            ("kaachan", "かあちゃんの台所"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "rice_size",
                    models.CharField(
                        choices=[
                            ("大", "ライス大"),
                            ("中", "ライス中"),
                            ("小", "ライス小"),
                        ],
                        default="中",
                        max_length=2,
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("price", models.IntegerField(default=650)),
                ("subsidy", models.IntegerField(default=230)),
                ("canceled", models.BooleanField(default=False)),
                ("canceled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "order_date", "vendor", "rice_size")},
            },
        ),
    ]
