# Generated by Django 5.2 on 2025-05-21 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lunch", "0002_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[("pending", "未発注"), ("sent", "発注済")],
                default="pending",
                max_length=20,
                verbose_name="ステータス",
            ),
        ),
    ]
